from . import darakjian_family
from . import darakjian_salesperson_assignment
from . import darakjian_wishlist
from . import darakjian_hold
from . import darakjian_rapaport
from . import darakjian_gem_card
from . import darakjian_appointment
from . import darakjian_service_ticket
from . import darakjian_commission
from . import res_partner
from . import product_product
from . import sale_order
